import { expect, test } from "@playwright/test";
import type { OntologyTermDataV2 } from "../src/api/types/ontologyTypes";

const windowShim = {
  location: {
    href: "http://localhost/",
    pathname: "/",
    search: "",
    hash: "",
  },
  history: {
    state: null,
    pushState: () => {},
    replaceState: () => {},
  },
  addEventListener: () => {},
  removeEventListener: () => {},
};

(globalThis as { document?: unknown; window?: unknown }).window = windowShim;
(globalThis as { document?: unknown }).document = {
  defaultView: windowShim,
};

const { TsClass } = require("../src/concepts/class") as typeof import(
  "../src/concepts/class"
);
const { TsTerm } = require("../src/concepts/term") as typeof import(
  "../src/concepts/term"
);
const TermLib = require("../src/Libs/TermLib").default as typeof import(
  "../src/Libs/TermLib"
).default;

const TERM_IRI = "http://example.test/term/root";
const PARENT_IRI = "http://example.test/term/parent";
const TARGET_IRI = "http://example.test/term/target";
const OUTPUT_IRI = "http://example.test/term/output";
const PROPERTY_IRI = "http://example.test/prop/part-of";
const INPUT_PROPERTY_IRI = "http://example.test/prop/has-input";
const OUTPUT_PROPERTY_IRI = "http://example.test/prop/has-output";
const AXIOM_KEY_IRI = "http://example.test/prop/is-inferred";
const AXIOM_VALUE_IRI = "http://example.test/term/generated-by-reasoner";
const UNKNOWN_AXIOM_VALUE_IRI = "http://example.test/term/unlabelled-source";
const SOME_VALUES_FROM = "http://www.w3.org/2002/07/owl#someValuesFrom";
const CARDINALITY = "http://www.w3.org/2002/07/owl#qualifiedCardinality";

function createClass(term: Partial<OntologyTermDataV2>) {
  return new TsClass(
    {
      iri: TERM_IRI,
      label: ["Root term"],
      type: ["class"],
      ontologyId: "test-ontology",
      linkedEntities: {
        [PARENT_IRI]: { label: ["Parent term"] },
        [TARGET_IRI]: { label: ["Target term"] },
        [OUTPUT_IRI]: { label: ["Output term"] },
        [PROPERTY_IRI]: { label: ["part of"] },
        [INPUT_PROPERTY_IRI]: { label: ["has input"] },
        [OUTPUT_PROPERTY_IRI]: { label: ["has output"] },
        [AXIOM_KEY_IRI]: { label: ["is inferred"] },
        [AXIOM_VALUE_IRI]: { label: ["generated by reasoner"] },
      },
      ...term,
    },
    [],
  );
}

function hasAxiomInfoButton(node: unknown): boolean {
  if (!node || typeof node !== "object") {
    return false;
  }
  if (Array.isArray(node)) {
    return node.some(hasAxiomInfoButton);
  }
  const element = node as {
    type?: string | ((...args: unknown[]) => unknown);
    props?: { children?: unknown };
  };
  if (
    typeof element.type === "function" &&
    element.type.name === "AxiomInfoButton"
  ) {
    return true;
  }
  return hasAxiomInfoButton(element.props?.children);
}

test.describe("TsClass.recursivelyBuildStructure", () => {
  test("returns link nodes for direct linked class IRIs", () => {
    const term = createClass({
      [TsTerm.SUBCLASS_PURL]: PARENT_IRI,
    });

    expect(term.recursivelyBuildStructure(TsTerm.SUBCLASS_PURL)).toEqual([
      {
        type: "link",
        iri: PARENT_IRI,
        label: "Parent term",
        target: "terms",
      },
    ]);
  });

  test("returns expression nodes for property restrictions", () => {
    const term = createClass({
      [TsTerm.SUBCLASS_PURL]: {
        [TsTerm.ON_PROPERTY_URI]: PROPERTY_IRI,
        [SOME_VALUES_FROM]: TARGET_IRI,
      },
    });

    expect(term.recursivelyBuildStructure(TsTerm.SUBCLASS_PURL)).toEqual([
      {
        type: "expression",
        left: {
          type: "link",
          iri: PROPERTY_IRI,
          label: "part of",
          target: "props",
        },
        relation: "someValuesFrom",
        right: {
          type: "link",
          iri: TARGET_IRI,
          label: "Target term",
          target: "terms",
        },
      },
    ]);
  });

  test("keeps top-level subclass arrays as separate structure nodes", () => {
    const term = createClass({
      [TsTerm.SUBCLASS_PURL]: [
        PARENT_IRI,
        {
          [TsTerm.ON_PROPERTY_URI]: INPUT_PROPERTY_IRI,
          [SOME_VALUES_FROM]: TARGET_IRI,
        },
        {
          [TsTerm.ON_PROPERTY_URI]: OUTPUT_PROPERTY_IRI,
          [SOME_VALUES_FROM]: OUTPUT_IRI,
        },
      ],
    });

    expect(term.recursivelyBuildStructure(TsTerm.SUBCLASS_PURL)).toEqual([
      {
        type: "link",
        iri: PARENT_IRI,
        label: "Parent term",
        target: "terms",
      },
      {
        type: "expression",
        left: {
          type: "link",
          iri: INPUT_PROPERTY_IRI,
          label: "has input",
          target: "props",
        },
        relation: "someValuesFrom",
        right: {
          type: "link",
          iri: TARGET_IRI,
          label: "Target term",
          target: "terms",
        },
      },
      {
        type: "expression",
        left: {
          type: "link",
          iri: OUTPUT_PROPERTY_IRI,
          label: "has output",
          target: "props",
        },
        relation: "someValuesFrom",
        right: {
          type: "link",
          iri: OUTPUT_IRI,
          label: "Output term",
          target: "terms",
        },
      },
    ]);
  });

  test("keeps cardinality values as literals", () => {
    const term = createClass({
      [TsTerm.SUBCLASS_PURL]: {
        [TsTerm.ON_PROPERTY_URI]: PROPERTY_IRI,
        [CARDINALITY]: "1",
      },
    });

    expect(term.recursivelyBuildStructure(TsTerm.SUBCLASS_PURL)).toEqual([
      {
        type: "expression",
        left: {
          type: "link",
          iri: PROPERTY_IRI,
          label: "part of",
          target: "props",
        },
        relation: "qualifiedCardinality",
        right: {
          type: "literal",
          value: "1",
        },
      },
    ]);
  });

  test("preserves labelled axioms and raw fallback values on direct class links", () => {
    const term = createClass({
      [TsTerm.SUBCLASS_PURL]: {
        value: PARENT_IRI,
        axioms: [
          { [AXIOM_KEY_IRI]: AXIOM_VALUE_IRI },
          { [AXIOM_KEY_IRI]: UNKNOWN_AXIOM_VALUE_IRI },
        ],
      },
    });

    expect(term.recursivelyBuildStructure(TsTerm.SUBCLASS_PURL)).toEqual([
      {
        type: "link",
        iri: PARENT_IRI,
        label: "Parent term",
        target: "terms",
        axioms: [
          {
            key: AXIOM_KEY_IRI,
            value: AXIOM_VALUE_IRI,
            keyLabel: "is inferred",
            valueLabel: "generated by reasoner",
          },
          {
            key: AXIOM_KEY_IRI,
            value: UNKNOWN_AXIOM_VALUE_IRI,
            keyLabel: "is inferred",
            valueLabel: UNKNOWN_AXIOM_VALUE_IRI,
          },
        ],
      },
    ]);
  });

  test("does not render axiom buttons unless explicitly enabled", () => {
    const term = createClass({
      [TsTerm.SUBCLASS_PURL]: {
        value: PARENT_IRI,
        axioms: [{ [AXIOM_KEY_IRI]: AXIOM_VALUE_IRI }],
      },
    });
    const nodes = term.recursivelyBuildStructure(TsTerm.SUBCLASS_PURL);

    expect(hasAxiomInfoButton(TermLib.renderClassStructure(term, nodes))).toBe(
      false,
    );
    expect(
      hasAxiomInfoButton(
        TermLib.renderClassStructure(term, nodes, { showAxioms: true }),
      ),
    ).toBe(true);
  });

  test("returns undefined when no structure can be built", () => {
    expect(
      createClass({}).recursivelyBuildStructure(TsTerm.SUBCLASS_PURL),
    ).toBeUndefined();

    expect(
      createClass({
        [TsTerm.SUBCLASS_PURL]: "http://example.test/term/unlinked",
      }).recursivelyBuildStructure(TsTerm.SUBCLASS_PURL),
    ).toBeUndefined();
  });
});
