export * from "./class";
export * from "./individual";
export * from "./ontology";
export * from "./property";
export * from "./term";
export * from "./termFactory";
export * from "./termset";
export * from "./types";
export * from "./skosClass";
